/* ================================================================
   VANI — Stimmen: Grüße, Funken, Saatworte
   ================================================================ */

const GRUESSE = {
  frueh: ['Guten Morgen.', 'Früh wach.', 'Der Tag ist noch leer.'],
  mittag: ['Mittendrin.', 'Guten Tag.', 'Zeit für ein paar Zeilen.'],
  nachmittag: ['Nachmittagslicht.', 'Schön, dass du da bist.', 'Weiter im Text.'],
  abend: ['Der Abend gehört den Seiten.', 'Guten Abend.', 'Zeit, die Tür zuzumachen.'],
  nacht: ['Noch wach.', 'Die beste Stunde.', 'Ganz leise jetzt.']
};
const GRUSS_UNTEN = [
  'Die Seiten warten schon.',
  'Alles ist da, wo du es gelassen hast.',
  'Kein Internet nötig. Nur du.',
  'Ein Satz reicht für den Anfang.',
  'Was liegen bleibt, bleibt liegen. Nichts verschwindet.',
  'Irgendwo hier liegt ein angefangener Gedanke.'
];
const GRUSS_LANGE_WEG = 'Schön, dass du wieder da bist.';

function grussZeile() {
  const h = new Date().getHours();
  const topf = h < 5 ? GRUESSE.nacht : h < 11 ? GRUESSE.frueh : h < 14 ? GRUESSE.mittag : h < 18 ? GRUESSE.nachmittag : h < 23 ? GRUESSE.abend : GRUESSE.nacht;
  const eigene = vomTyp('gruss').map((g) => g.text).filter(Boolean);
  if (eigene.length && Math.random() < .35) return zufall(eigene);
  return zufall(topf);
}

const FUNKEN = [
  'Ein Ort, an den niemand zurückkehrt — außer einmal im Jahr.',
  'Jemand findet einen Brief, der eindeutig an ihn gerichtet ist. Nur ist er hundert Jahre alt.',
  'Das Haus tauscht nachts die Zimmer. Alle tun so, als wäre das normal.',
  'Zwei Menschen, die sich jeden Tag sehen, sprechen zum ersten Mal.',
  'Etwas, das man aus Versehen behalten hat. Und jetzt ist es zu spät, es zurückzugeben.',
  'Die letzte Nacht in einer Wohnung. Die Wände sind schon leer.',
  'Ein Gespräch, das nur aus dem besteht, was nicht gesagt wird.',
  'Der Moment, in dem eine Lüge zur Wahrheit wird, weil alle sie glauben.',
  'Jemand kann nur an einem einzigen Ort auf der Welt schlafen.',
  'Eine Landkarte mit einem Ort, der auf keiner anderen Karte ist.',
  'Das Meer gibt etwas zurück. Nicht das, was man vermisst hat.',
  'Ein Beruf, den es nicht gibt: Was macht die Person den ganzen Tag?',
  'Der erste Schnee, aus der Sicht von jemandem, der ihn zum letzten Mal sieht.',
  'Ein Zug hält an einem Bahnhof, der nicht im Fahrplan steht.',
  'Jemand erbt ein Notizbuch. Die Hälfte ist schon vollgeschrieben — von wem?',
  'Was in der Woche zwischen den Jahren passiert, zählt nicht. Sagt man.',
  'Der Geruch, der einen sofort zehn Jahre zurückwirft.',
  'Zwei Fremde warten zusammen. Worauf, weiß nur einer von beiden.',
  'Eine Stadt, in der Vergessen als Höflichkeit gilt.',
  'Das Licht im Nachbarhaus geht seit drei Nächten nicht mehr aus.',
  'Jemand schreibt seit Jahren Briefe an eine Adresse, die es nicht gibt. Heute kommt eine Antwort.',
  'Das Haus wird verkauft. Beim Ausräumen findet sich eine Tür, die in keinem Grundriss steht.',
  'Eine Stimme im Radio, mitten in der Nacht, sagt deinen Namen. Nur einmal.',
  'Der Jahrmarkt kommt dieses Jahr einen Tag zu früh. Niemand hat ihn bestellt.',
  'Zwei Geschwister teilen sich eine Erinnerung — aber jede Hälfte erzählt sie anders.',
  'In der Bibliothek steht ein Buch, das jedes Mal anders endet.',
  'Jemand kehrt in die alte Wohnung zurück. Der eigene Name steht noch am Klingelschild — frisch gedruckt.',
  'Der Fluss friert zum ersten Mal seit hundert Jahren zu. Etwas liegt im Eis.',
  'Ein Kind fragt: „Wo warst du, bevor du hier warst?“ Und niemand am Tisch kann antworten.',
  'Die letzte Nachricht wurde nie abgeschickt. Der Entwurf ist noch da.',
  'Jemand sammelt die letzten Sätze fremder Gespräche. Heute fällt einer, der alles ändert.',
  'Ein Sommer, in dem alle Uhren der Stadt eine Minute nachgehen. Nur eine nicht.',
  'Das Gewitter kommt näher, und mit ihm ein Geruch aus der Kindheit.',
  'Im Nachlass liegt eine Kassette, auf der jemand die Zukunft voraussagt — mit deiner Stimme.',
  'Eine Person erkennt auf einem Flohmarkt etwas wieder, das sie nie besessen haben dürfte.',
  'Alle Fenster des Hauses zeigen dieselbe Aussicht. Nur eines zeigt gestern.',
  'Ein Kind erfindet einen unsichtbaren Freund. Am Elternabend sitzt dessen Mutter im Flur.',
  'Der Schlüssel wurde vererbt, aber niemand weiß, zu welcher Tür er gehört.',
  'Ein ganzes Dorf hat denselben Traum und verschweigt ihn am Morgen.',
  'Im Hotelzimmer klingelt ein Telefon, obwohl keines angeschlossen ist.',
  'Jemand bekommt jedes Jahr am selben Tag eine Postkarte ohne Absender. Dieses Jahr bleibt sie leer.',
  'Die berühmteste Fotografie der Stadt zeigt im Hintergrund jemanden, der heute noch genauso aussieht.',
  'Eine Schauspielerin vergisst nach der Vorstellung, welche ihrer Erinnerungen wirklich ihre sind.',
  'Der Busfahrer hält jeden Abend an einer Haltestelle, an der nie jemand wartet — bis heute.',
  'Zwei Feinde müssen gemeinsam eine Nachricht überbringen, die keiner von beiden gelesen haben darf.',
  'Die Wohnung über dir steht leer. Trotzdem wird dort jede Nacht ein Stuhl verrückt.',
  'Jemand findet den ersten Satz eines Romans in der eigenen Handschrift. Der Rest ist verbrannt.',
  'Ein Lied taucht in drei Lebensgeschichten auf, die nichts miteinander zu tun haben dürften.',
  'Der Hund bringt etwas aus dem Wald zurück, das vor zwanzig Jahren vergraben wurde.',
  'Eine Stadt feiert einen Feiertag, dessen Anlass niemand mehr kennt.',
  'Jemand ist berühmt für eine Heldentat, an die er sich nicht erinnern kann.',
  'Das letzte Kino zeigt einen Film, in dem das Publikum selbst vorkommt.',
  'In der Nacht vor dem Umzug erscheint eine Nachricht unter der Tapete.',
  'Eine Person hört zum ersten Mal die eigene Stimme als Kind und erkennt ein Versprechen wieder.',
  'Der Briefträger liefert einen Brief an eine Person, die erst morgen einzieht.',
  'Am Ende jeder Straße steht dasselbe rote Auto.',
  'Ein Fremder kennt den Spitznamen, den seit der Kindheit niemand mehr benutzt hat.',
  'Eine Familie erbt ein Haus samt einer Regel: Nach Mitternacht darf niemand den eigenen Namen sagen.',
  'Der Strom fällt aus. Im schwarzen Fenster spiegelt sich ein Zimmer, das hinter dir nicht existiert.',
  'Jemand schreibt die Wahrheit in ein Tagebuch und entdeckt am Morgen Korrekturen am Rand.',
  'Zwei Menschen erinnern sich an dieselbe erste Begegnung — an verschiedenen Orten.',
  'Eine Bibliothekarin findet Rückgabekarten aus einem Jahr, das noch nicht begonnen hat.',
  'Der Schnee bewahrt Fußspuren, die mitten auf dem See beginnen.',
  'Ein Musiker spielt eine Melodie, die nur Menschen erkennen, die etwas verloren haben.',
  'Die Hauptfigur weiß, dass sie in einer Geschichte lebt — aber nicht, in welcher.',
  'Jemand kommt nach Hause und alle Fotos zeigen plötzlich eine Person weniger.',
  'Ein altes Navigationsgerät führt nur noch zu Orten, an denen Abschiede stattgefunden haben.',
  'Die Nachtwache im Museum bemerkt, dass auf einem Gemälde jeden Morgen eine Tür weiter offen steht.',
  'Ein Kind schickt eine Flaschenpost den Fluss hinab. Sie kommt am selben Abend von oben zurück.',
  'Jemand erhält eine Rechnung für eine Reise, die nie stattgefunden hat.',
  'Der letzte Satz steht fest. Nur die Geschichte weigert sich, dorthin zu gehen.',
  'Eine Freundschaft beginnt mit einem gestohlenen Gegenstand und endet mit seiner Rückgabe.',
  'Am Bahnsteig verabschieden sich zwei Menschen. Nur einer weiß, dass der Zug nicht existiert.',
  'Die Nachbarin grüßt jeden Morgen mit einem anderen Namen. Heute mit deinem.',
  'In einer Schublade liegt ein Schlüsselbund mit Schlüsseln zu Häusern, die man nie betreten hat. Einer davon wird warm.',
  'Der Wetterbericht im Radio beschreibt seit Tagen ein Wetter, das nur in deiner Straße herrscht.',
  'Eine Frau bekommt einen Anruf von sich selbst. Die Stimme klingt älter und ruhiger.',
  'Ein Kind sammelt Schatten. In einer Streichholzschachtel liegt der, den es am liebsten mag.',
  'Jemand kauft auf dem Flohmarkt ein Fotoalbum und erkennt auf der letzten Seite die eigene Küche.',
  'Der Leuchtturm ist seit Jahren stillgelegt. Trotzdem sieht man ihn jede Nacht einmal kreisen.',
  'Jemand schreibt Briefe an den Menschen, der nach ihm in die Wohnung zieht.',
  'Die Stadt hat eine Straße, die nur in eine Richtung existiert. Zurück gibt es sie nicht.',
  'Das Kind fragt: „Was war vor dem Anfang?“ Die Großmutter antwortet erstaunlich genau.',
  'Ein Mann findet in seinem Mantel eine Kinokarte für einen Film, der erst nächste Woche anläuft.',
  'Im Treppenhaus steht seit Wochen ein Stuhl. Niemand hat ihn hingestellt. Niemand trägt ihn weg.',
  'Eine Bäckerin kennt jeden Kunden am Geruch. Heute kommt einer, der nach nichts riecht.',
  'Zwei Menschen teilen sich ein Haus, aber nie dieselbe Tageszeit.',
  'Das Radio spielt ein Lied, das nur deine Familie kennt. Es wurde nie aufgenommen.',
  'Jemand schreibt seit Jahren an der Entschuldigung für etwas, das noch nicht passiert ist.',
  'Nach dem Umzug hängen in der neuen Wohnung schon Vorhänge. In genau deiner Lieblingsfarbe.',
  'Ein Dorf feiert jeden Sommer die Rückkehr von jemandem, der nie weggegangen ist.',
  'Die Uhr auf dem Bahnhof geht nach. Nur für Menschen, die zu früh sind.',
  'Jemand hört auf dem Dachboden ein Geräusch, das sich wie das eigene Lachen von früher anhört.',
  'Der Briefkasten enthält einen Brief, der an dich adressiert ist — in deiner eigenen, kindlichen Handschrift.',
  'Eine Tür in der Wohnung führt manchmal in den Flur, manchmal in einen Garten, den es nicht gibt.',
  'Ein Arzt diagnostiziert Heimweh nach einem Ort, an dem der Patient nie war.',
  'Der Hund erkennt auf der Straße jemanden wieder, den du nicht kennst. Er ist außer sich vor Freude.',
  'Jede Nacht steht ein weiteres Möbelstück im Garten. Alle aus demselben Kinderzimmer.',
  'Jemand hat seit zwanzig Jahren dieselbe Nummer im Handy, ohne je anzurufen. Heute klingelt sie.',
  'Das Schwimmbad hat eine Bahn, in der man langsamer altert. Die Warteliste ist lang.',
  'Ein Fremder bittet dich, ihm seinen eigenen Namen zu sagen.',
  'Eine Frau führt Buch über alle Sätze, die sie nicht gesagt hat. Heute ist das Heft voll.',
  'Im Schnee vor dem Haus liegt ein Brief. Die Tinte ist noch feucht.',
  'Ein Koch kann Erinnerungen kochen. Ein Gast bestellt eine, die er vergessen möchte.',
  'Die alte Telefonzelle am Ende der Straße nimmt nur Gespräche an, die nie geführt wurden.',
  'Jemand wacht in einem Zimmer auf, das genauso aussieht wie sein eigenes — nur spiegelverkehrt.',
  'Die Kinder im Haus spielen ein Spiel, dessen Regeln niemand erklären kann. Die Erwachsenen kennen es von früher.',
  'Auf dem Friedhof steht ein Grabstein mit einem Datum in der Zukunft.',
  'Eine Schneiderin näht für jemanden einen Mantel, der erst passen wird, wenn er verziehen hat.',
  'Der Mieter über dir geht jede Nacht um drei dieselbe Strecke. Heute zählst du seine Schritte mit: Es ist deine Wohnung.',
  'Ein Musiker spielt auf der Straße ein Lied, das du vor Jahren geträumt hast.',
  'Jemand hat das gesamte Leben in Listen aufgeschrieben. Nur ein Tag fehlt.',
  'Die Brücke ist gesperrt — für alle, die noch wissen, warum sie sie überqueren wollen.',
  'Im Antiquariat liegt dein Tagebuch. Mit einem Vorwort von jemand anderem.',
  'Ein Mann erhält eine Postkarte aus einer Stadt, die erst gebaut wird.',
  'Jede Familie im Dorf hat denselben Gegenstand versteckt. Niemand weiß, was er bedeutet.',
  'Eine Frau erkennt auf einem Gemälde ihren Garten. Das Bild ist dreihundert Jahre alt.',
  'Ein Kind verspricht, etwas erst zu erzählen, „wenn es sicher ist“. Jahre später ruft es an.',
  'Das letzte Blatt am Baum fällt nicht. Die Leute kommen schon von weit her, um es anzusehen.',
  'Jemand bekommt eine Einladung zu seiner eigenen Abschiedsfeier. Er hat nicht vor zu gehen.',
  'Die Wohnung schrumpft jede Nacht ein kleines Stück. Erst merkt es niemand.',
  'Ein Paar trifft sich jeden Tag zum ersten Mal. Nur einer von beiden weiß es.',
  'Ein Junge findet im Wald ein Klavier. Es ist gestimmt.',
  'Die Fähre legt ab, obwohl kein Wasser da ist.',
  'Jemand versteckt einen Brief im Buch einer Bibliothek. Zwanzig Jahre später steht dort eine Antwort.',
  'Die Mutter erzählt ein Märchen, das sie sich ausdenkt. Am nächsten Tag steht es in der Zeitung.',
  'In einem Haus klingelt es immer einmal zu viel.',
  'Eine Stadt, in der man tauschen kann: ein Jahr Erinnerung gegen ein Jahr Zukunft.',
  'Der Weg zur Schule ist heute zehn Minuten länger. Die Straßen sind dieselben.',
  'Ein Mann bewahrt die letzten Worte seiner Großmutter auf einem Kassettenband. Heute spult das Band von allein zurück.',
  'Ein Boot treibt den Fluss hinauf.',
  'Jemand sieht zum ersten Mal das Meer — und erkennt es wieder.',
  'Das Kind zeichnet jeden Tag dasselbe Haus. Heute hat es ein Fenster mehr.',
  'Eine Lehrerin bekommt einen Aufsatz zurück, den sie selbst als Kind geschrieben hat.',
  'Eine Telefonnummer, die auf allen Zetteln der Stadt auftaucht, aber niemand wählt sie.',
  'Ein Mann behauptet, der Regen in dieser Stadt sei jedes Mal derselbe Regen.',
  'Eine Ärztin kann hören, wie alt eine Lüge ist.',
  'Zwei Schwestern streiten seit dreißig Jahren über eine Geschichte, die keine von beiden erlebt hat.',
  'Die Stadt baut einen Bahnhof für einen Zug, der erst in fünfzig Jahren kommt.',
  'Das Mietshaus hat eine Wohnung zu viel. Alle tun, als hätten sie es nie bemerkt.',
  'Jemand lernt eine Sprache, die nur noch ein Mensch spricht. Heute treffen sie sich.',
  'Ein Hochzeitsfoto, auf dem jedes Jahr eine Person mehr zu sehen ist.',
  'Der Wind bringt Zettel. Auf jedem steht ein Satz, den du heute noch sagen wirst.',
  'Ein Nachtportier führt ein Gästebuch für die, die nie angekommen sind.',
  'Die Schule hat einen Raum, der nur einmal im Jahr aufgeschlossen wird. Niemand spricht darüber, was drin ist.',
  'Jemand erbt ein Haus mit der Auflage, darin jeden Abend ein Fenster zu öffnen. Welches, steht nicht dabei.',
  'Eine Frau verkauft Abschiede. Gute Ware, sagt sie, die reicht ein Leben lang.',
  'Der letzte Gast im Café bleibt sitzen, als wüsste er, dass das Licht sonst ausgeht.',
  'Ein Kind hat einen Zwilling, den nur die Fotos zeigen.',
  'Der Nachbar ist tot, aber sein Garten wird jeden Abend gegossen.',
  'In einer Stadt kann man nachts die Gedanken der anderen an den Fenstern lesen. Nur deine Scheibe bleibt leer.',
  'Jemand restauriert alte Filme und findet in jedem dieselbe Frau im Hintergrund.',
  'Ein Mann geht jeden Tag denselben Weg — und jeden Tag ist ein Haus weniger da.',
  'Du findest die Liste deiner Wünsche von vor zehn Jahren. Alle sind abgehakt. Von fremder Hand.',
  'Die Katze bringt jeden Morgen einen Gegenstand aus einem Haus, das du nicht kennst.',
  'Eine Stadt, in der niemand die Uhrzeit kennt, aber alle pünktlich sind.',
  'Jemand spricht im Schlaf einen Namen. Am Morgen steht er an der Tür.',
  'Nach dem Brand liegt im Schutt ein Zimmer, das unversehrt ist. Es gehörte zu keinem Haus.',
  'Ein Bergdorf feiert den Tag, an dem das Tal zurückkam.',
  'Der Briefträger bringt Briefe aus, die erst morgen geschrieben werden. Er hält sich an die Regeln.',
  'Jemand rettet einen Fremden vor dem Ertrinken. Der Fremde sagt: „Nicht schon wieder.“',
  'Ein Dorf ohne Spiegel. Ein Gast bringt einen mit.',
  'Jeden Geburtstag liegt ein Stein vor der Tür. Heute ist er warm.'
];
const FUNKE_WER = [
  'Eine Frau, die Karten für Orte zeichnet, die es nicht mehr gibt,',
  'Ein Junge mit einem geliehenen Namen,',
  'Die letzte Leuchtturmwärterin,',
  'Ein Übersetzer, der an einem einzigen Wort scheitert,',
  'Jemand, der nie zweimal denselben Weg geht,',
  'Eine alte Frau, die alle Geburtstage der Stadt auswendig kennt,',
  'Ein Kind, das Dinge findet, bevor sie verloren gehen,',
  'Der Mann, der die Bahnhofsuhr von Hand stellt,',
  'Eine Bühnenbildnerin, die in fremden Zimmern Erinnerungen versteckt,',
  'Der Sohn eines Mannes, über den alle lügen,',
  'Eine Diebin, die nur Dinge stiehlt, die niemand vermisst,',
  'Ein Pilot, der sich weigert, denselben Himmel zweimal zu überfliegen,',
  'Die jüngste Person in einer sehr alten Familie,',
  'Ein Polizist, der den eigenen Vermisstenfall bearbeitet,',
  'Eine Musikerin, die jedes Lied nur einmal spielen kann,',
  'Jemand, der fremde letzte Sätze sammelt,',
  'Ein Uhrmacher, der seit Jahren keine Uhr mehr repariert, aber jeden Tag den Laden öffnet,',
  'Eine Sängerin, die ihre Stimme verloren hat und jetzt Briefe für andere schreibt,',
  'Ein Junge, der jede Nacht dasselbe Haus träumt,',
  'Die Frau, die den Schnee vom letzten Winter aufbewahrt,',
  'Ein Gärtner, der nur Pflanzen zieht, die es nicht mehr gibt,',
  'Der Mann mit den drei Pässen, die alle auf verschiedene Namen lauten,',
  'Eine Bibliothekarin, die Bücher nach dem Geruch ihrer Leser ordnet,',
  'Ein Kind, das nie lügt und deshalb niemand glaubt,',
  'Eine Zugschaffnerin, die die Namen aller Fahrgäste kennt — auch der schlafenden,',
  'Ein alter Fischer, der nur noch nach Dingen fischt, die jemand verloren hat,',
  'Eine Apothekerin, die Gegenmittel für Erinnerungen mischt,',
  'Der Junge vom Leuchtturm, der noch nie auf dem Festland war,',
  'Eine Taxifahrerin, die nur Menschen mitnimmt, die nicht wissen, wohin,',
  'Der Mann, der Briefe zurückbringt, die nie hätten abgeschickt werden dürfen,',
  'Eine Frau, die den Garten ihrer Kindheit Stück für Stück zurückkauft,',
  'Ein Kartograf, der Orte einzeichnet, bevor sie entstehen,',
  'Ein Mädchen, das Gespräche sammelt wie andere Briefmarken,',
  'Der letzte Mensch, der die alte Ortssprache spricht,',
  'Ein Vater, der seiner Tochter jeden Abend eine andere Version derselben Geschichte erzählt,',
  'Eine Frau, die für fremde Menschen die Wohnungen ausräumt und dabei ihr eigenes Leben findet,',
  'Ein Hotelportier, der die Gäste nach ihren Träumen fragt,',
  'Ein Mann, der die Zeit nach Gerüchen einteilt,',
  'Eine Tänzerin, die sich nur noch bewegt, wenn niemand hinsieht,',
  'Ein Kind, das glaubt, der Regen falle nur für es allein,'
];
const FUNKE_WO = [
  'in einem Haus, das nachts die Zimmer tauscht,',
  'auf einer Fähre, die nur bei Nebel fährt,',
  'in der letzten Telefonzelle des Landes,',
  'in einer Bibliothek, in der geflüstert wird, obwohl sie leer ist,',
  'am Rand eines Dorfes, das auf keiner Karte steht,',
  'in einem Sommer, der nicht enden will,',
  'im Treppenhaus zwischen zwei Wohnungen,',
  'an einem Bahnsteig, an dem nie ein Zug hält,',
  'hinter der Bühne eines längst geschlossenen Theaters,',
  'in einem Hotel, dessen Zimmernummern sich jede Nacht ändern,',
  'auf einer Brücke, die nur in eine Richtung führt,',
  'im Archiv einer Stadt, die ihren Namen gewechselt hat,',
  'in einem Tunnel unter schwarzem Wasser,',
  'in einem roten Buch voller fremder Handschriften,',
  'auf einem Friedhof, auf dem ein Grab zu viel steht,',
  'in einem Auto, das seit Jahren am selben Straßenrand wartet,',
  'in einem Café, in dem jeder Tisch eine andere Jahreszeit hat,',
  'auf dem Dachboden eines Hauses, das nächste Woche abgerissen wird,',
  'in einer Kleinstadt, in der nachts alle Straßenlaternen in eine Richtung zeigen,',
  'im Wartezimmer eines Arztes, der nie kommt,',
  'auf einer Insel, die nur bei Ebbe existiert,',
  'in der letzten Nacht vor dem Umzug,',
  'im Schwimmbad nach Betriebsschluss,',
  'in einem Zug, der seit Stunden an derselben Stelle steht,',
  'auf einer Hochzeit, zu der niemand eingeladen wurde,',
  'in einer Wohnung, in der noch die Möbel des Vormieters stehen,',
  'am Rand eines Dorfes, das sich selbst vergessen hat,',
  'in einem Kino, das nur einen Film zeigt — seit vierzig Jahren,',
  'an einem Strand im November,',
  'in einem Krankenhausflur um vier Uhr morgens,',
  'auf dem Spielplatz, auf dem man selbst Kind war,',
  'im Flur einer Schule, in den Sommerferien,',
  'in einer Gärtnerei, in der die Pflanzen flüstern, wenn es regnet,',
  'in einem Lagerhaus voller unabgeholter Pakete,',
  'in einer Nacht, in der der Strom in der ganzen Stadt ausfällt,',
  'in der Wohnung über dem Laden, der die ganze Nacht offen hat,',
  'auf einer Brücke, die seit Jahren gesperrt ist,',
  'in einem Hinterhof mit einem Baum, den niemand gepflanzt hat,',
  'in einem Zimmer, das man nur durch einen Schrank betritt,',
  'am Fenster, an dem schon die Großmutter stand,'
];
const FUNKE_ABER = [
  'aber jemand hat die Wahrheit zuerst erzählt.',
  'aber der Brief kommt zwölf Jahre zu spät an.',
  'aber das Meer gibt nichts zurück.',
  'aber diesmal brennt kein Licht im Fenster.',
  'aber der Name im Register ist der eigene.',
  'aber heute klopft es zweimal.',
  'aber der Schlüssel passt plötzlich nicht mehr.',
  'aber es liegt Schnee. Mitten im August.',
  'aber die Aufnahme kennt das Ende schon.',
  'aber heute erinnert sich niemand an diese Person.',
  'aber das Licht geht an, bevor jemand den Schalter berührt.',
  'aber auf der Rückseite steht das morgige Datum.',
  'aber beide haben denselben Traum verschwiegen.',
  'aber der letzte Satz wurde von jemand anderem geschrieben.',
  'aber die Tür war die ganze Zeit offen.',
  'aber diesmal kommt eine Antwort.',
  'aber jemand hat alle Uhren im Haus um eine Stunde vorgestellt.',
  'aber die Person, auf die gewartet wird, sitzt längst mit am Tisch.',
  'aber im Brief fehlt genau der Satz, auf den es ankäme.',
  'aber der Hund will nicht über die Schwelle.',
  'aber draußen fällt Schnee, obwohl niemand das erklären kann.',
  'aber der Spiegel zeigt den Raum ohne die Person davor.',
  'aber der Fremde weiß Dinge, die nur die Familie weiß.',
  'aber die Landkarte hat seit heute einen neuen Ort.',
  'aber die Stimme am Telefon kennt den Kosenamen aus der Kindheit.',
  'aber das Foto zeigt die Szene aus einem Winkel, aus dem niemand fotografiert haben kann.',
  'aber das Licht geht aus, wenn jemand die Wahrheit sagt.',
  'aber die Wohnung riecht nach dem Essen, das es morgen geben wird.',
  'aber in der Schublade liegt der eigene Abschiedsbrief — ungeschrieben.',
  'aber der Zug fährt heute in die andere Richtung.',
  'aber das Kind nennt den Besucher beim Namen.',
  'aber der Schnee bleibt nur auf einem einzigen Dach liegen.',
  'aber der Schlüssel passt in jede Tür der Straße.',
  'aber jemand hat das Ende der Geschichte schon auf die Wand geschrieben.',
  'aber das Meer zieht sich zurück und kommt nicht wieder.',
  'aber alle im Raum haben dieselbe Narbe.',
  'aber der erste Satz des Briefes ist der letzte, den jemand je gesagt hat.',
  'aber die Nachbarn stellen heute alle Stühle auf die Straße.',
  'aber der Baum vor dem Fenster trägt Früchte mitten im Januar.',
  'aber das Klavier spielt, wenn niemand im Zimmer ist.'
];
const FUNKE_FRAGEN = [
  'Welche Wahrheit würde diese Figur nur einem Fremden sagen?',
  'Was ist im Hintergrund passiert, während alle auf die Hauptsache sahen?',
  'Welcher Gegenstand weiß mehr über die Geschichte als ihre Figuren?',
  'Was wäre der erste Satz, wenn du das Ende schon kennen würdest?',
  'Wovor hat die mutigste Person im Raum heimlich Angst?',
  'Welche Erinnerung teilen zwei Figuren, obwohl nur eine dabei war?',
  'Was will jemand unbedingt zurückgeben — und warum geht es nicht?',
  'Welche Tür würde deine Figur niemals freiwillig öffnen?',
  'Wer fehlt in dieser Szene, ist aber in jedem Satz spürbar?',
  'Was geschieht fünf Minuten nach dem vermeintlichen Ende?',
  'Was sagt die Hauptfigur nur, wenn sie glaubt, niemand hört zu?',
  'Wem gehört der Gegenstand, der in dieser Szene am meisten Platz einnimmt?',
  'Welche Lüge erzählt sich die Figur selbst so oft, dass sie inzwischen stimmt?',
  'Was würde passieren, wenn in dieser Szene niemand spricht?',
  'Welches Geräusch gehört zu dieser Szene und wird nie erwähnt?',
  'Was hat die Figur heute schon getan, bevor die Geschichte beginnt?',
  'Welche Frage darf in dieser Familie nicht gestellt werden?',
  'Was weiß der Leser, das die Figur nicht wissen darf?',
  'Welcher Raum im Haus wird nie beschrieben — und warum?',
  'Was tut die Figur mit den Händen, während sie zuhört?',
  'Welchen Satz hat sie schon zu oft gehört?',
  'Was liegt in der Jackentasche — und seit wann?',
  'Wenn die Szene ein Wetter wäre: welches?',
  'Wer hat den Tisch gedeckt, an dem jetzt gestritten wird?',
  'Was war das letzte Geschenk, das die Figur jemandem gemacht hat?',
  'Welches Lied würde laufen, wenn das hier ein Film wäre — und wer hat es ausgesucht?',
  'Was würde die Figur als Allererstes retten, wenn es brennt?',
  'Welche Angewohnheit hat die Figur von ihrer Mutter, ohne es zu merken?',
  'Was wäre, wenn der Nebensatz die Hauptsache ist?',
  'Welche Tür in dieser Geschichte wurde noch nie geöffnet?',
  'Was schmeckt die Figur, während sie das liest?',
  'Warum heute? Warum nicht gestern oder nie?',
  'Was ist in dieser Geschichte teurer als Geld?',
  'Wer beobachtet die Szene, ohne darin vorzukommen?',
  'Was hätte die Figur mit zehn Jahren über diesen Moment gesagt?',
  'Welcher Gegenstand in der Szene ist kaputt — und wer weiß davon?',
  'Was ist das Letzte, was die Figur vor dem Einschlafen denkt?',
  'Wie riecht der Ort, an dem sie sich sicher fühlt?',
  'Was verschweigt die Erzählstimme — nicht die Figur?',
  'Was wäre der Titel dieser Szene, wenn ihn die Nebenfigur wählen dürfte?'
];
const FUNKE_FORMEN = [
  'Schreib nur den ersten und den letzten Satz einer Szene. Lass den Weg dazwischen noch dunkel.',
  'Schreib eine Seite ausschließlich aus Dingen, die niemand ausspricht.',
  'Beginne mit einem Geräusch. Verrate erst im letzten Absatz, woher es kam.',
  'Schreib dieselbe Minute zweimal — aus zwei Erinnerungen, die einander widersprechen.',
  'Lass einen Gegenstand die Szene erzählen, ohne ihn lebendig zu machen.',
  'Schreib eine Liste, die langsam zu einer Geschichte wird.',
  'Schreib einen Abschied, in dem niemand geht.',
  'Beginne mit: „Ich wusste damals noch nicht, dass …“ — und streich den Satz später wieder.',
  'Schreib eine Szene rückwärts: vom letzten Bild bis zum ersten Blick.',
  'Lass den Hintergrund die Wahrheit erzählen, während vorne gelogen wird.',
  'Schreib eine Szene nur aus dem, was auf dem Tisch liegt.',
  'Erzähl ein ganzes Jahr in zwölf Sätzen — einer pro Monat.',
  'Beschreibe eine Person nur über das, was sie in der Tasche hat.',
  'Schreib einen Dialog, in dem beide über etwas anderes reden, als sie meinen.',
  'Lass die Szene beim Abwasch spielen. Die Wahrheit kommt mit dem letzten Teller.',
  'Schreib einen Brief, der nie abgeschickt wird — und die Antwort, die trotzdem kommt.',
  'Erzähl den Moment aus der Sicht des Zimmers.',
  'Schreib eine Liste von zehn Dingen, die in der Wohnung fehlen. Die zehnte ist eine Person.',
  'Beschreibe einen Streit nur über Gegenstände, die dabei bewegt werden.',
  'Schreib einen Text, in dem jeder Satz ein Wort weniger hat als der vorige.',
  'Erzähl eine Begegnung zweimal: einmal aus Sicht dessen, der bleibt, einmal aus Sicht dessen, der geht.',
  'Schreib eine Szene, die nur aus Fragen besteht.',
  'Lass eine Nebenfigur die ganze Szene tragen. Die Hauptfigur kommt nicht vor.',
  'Schreib einen Absatz, in dem ein Gefühl nicht genannt, aber in jedem Satz spürbar ist.',
  'Beschreibe den Heimweg, als wäre es das letzte Mal.',
  'Schreib ein Gespräch, das nur aus dem besteht, was auf Zettel geschrieben wird.',
  'Erzähl vom ersten Schnee — aber ohne das Wort Schnee.',
  'Schreib eine Gebrauchsanweisung für etwas, das man nicht erklären kann.',
  'Schreib eine Szene, die mit einem Geruch beginnt und mit einem Geräusch endet.',
  'Beschreibe deinen Lieblingsort so, dass man ihn nicht wiedererkennt.',
  'Schreib einen Nachruf auf etwas, das nicht sterben kann.',
  'Erzähl die Geschichte in Nachrichten, die sich zwei Menschen schicken. Einer antwortet nicht mehr.',
  'Schreib eine Szene mit genau drei Sätzen — der mittlere verändert alles.',
  'Lass eine Figur etwas erklären, was sie selbst nicht versteht.',
  'Schreib eine Seite, auf der das Wort „ich“ nicht vorkommt.',
  'Erzähl einen Tag nur über die Türen, die geöffnet und geschlossen werden.',
  'Schreib die Szene als Wetterbericht.',
  'Schreib einen Text, der mit dem letzten Wort des vorigen Textes beginnt.',
  'Beschreibe eine Hand. Nur eine Hand. Bis man den ganzen Menschen kennt.',
  'Schreib eine Szene, in der jemand etwas zurückbekommt, das er nie verloren hat.'
];
const FUNKE_SAETZE = [
  '„Sag mir nur, warum du das Licht angelassen hast.“',
  'Der Schlüssel war warm, als hätte ihn gerade jemand gehalten.',
  'Im Rückspiegel saß niemand, aber der Gurt war geschlossen.',
  'Sie hatte sich vorgenommen, seinen Namen heute nicht zu sagen.',
  'Der erste Schuss war vielleicht nur das Klingeln in seinen Ohren.',
  'Auf dem Umschlag stand eine Adresse, die es nur in ihrer Erinnerung gab.',
  '„Du warst schon einmal hier“, sagte das Kind.',
  'Als die Musik aufhörte, hörten sie das Klopfen.',
  'Er lächelte so, als wäre dies eine gute Nachricht.',
  'Die Geschichte kannte den Weg, auch wenn ich ihn nicht kannte.',
  'Das Haus hatte die Angewohnheit, nachts ein wenig weiter vom Fluss wegzurücken.',
  'Sie hatte sich das Ende so oft vorgestellt, dass es keinen Platz mehr dafür gab.',
  'Der Brief war in seiner Handschrift, aber er hatte ihn nie geschrieben.',
  'Am Morgen nach dem Sturm stand das Boot im Garten, als hätte es immer dort gestanden.',
  'Niemand hatte ihr gesagt, dass man das Vergessen üben muss.',
  '„Bleib“, sagte er, und meinte: „Geh, bevor ich es noch einmal sage.“',
  'Die Stadt roch nach dem Regen, der erst morgen fallen würde.',
  'Er zählte die Stufen, wie er es als Kind getan hatte, und kam auf eine mehr.',
  'Es war die Sorte Stille, die man nur hört, wenn man sie bricht.',
  'Ihr Großvater hatte ihr beigebracht, wie man wartet. Nicht, wie man aufhört damit.',
  'Der Schlüssel lag noch unter der Matte, aber die Tür war nicht mehr da.',
  'Sie sprachen über das Wetter, wie man über Tote spricht.',
  'Das Foto war unscharf, nur die Hand am Rand nicht.',
  'Es gibt Nächte, in denen die Wohnung größer ist als tagsüber.',
  'Er hatte gelernt, dass ein Satz zu viel schlimmer ist als einer zu wenig — und sagte trotzdem den einen.',
  'Das letzte Mal, dass sie gelacht hatte, war am Telefon gewesen, mit jemandem, der nicht mehr anrief.',
  'Der Zug fuhr ein, und für einen Moment sah jeder auf dem Bahnsteig aus, als würde er erwartet.',
  'Im Flur roch es nach dem Kuchen, den es heute nicht gegeben hatte.',
  'Sie faltete den Brief so, wie man jemanden umarmt, den man nicht mehr anfassen darf.',
  'Draußen wurde es hell, ohne dass jemand es erlaubt hätte.',
  'Er war kein schlechter Mensch. Er war nur immer im falschen Zimmer.',
  'Manche Häuser vergessen die Menschen, die darin gewohnt haben. Dieses nicht.',
  'Das Lied lief, und sie wusste nicht mehr, ob sie es kannte oder ob es sie kannte.',
  'Seit dem Winter sagten sie sich nur noch die Dinge, die man auch einer Katze sagt.',
  'Der Garten hatte in diesem Jahr beschlossen, nichts zu tragen.',
  'Er kam zurück wie ein Wort, das man zu lange gesucht hat: plötzlich und zu spät.',
  'In ihrem Kalender stand für heute nur ein Name, den sie nicht kannte.',
  'Das Meer war an diesem Morgen so ruhig, als hätte es etwas beschlossen.',
  'Sie hatte den Koffer gepackt, bevor sie wusste, wohin.',
  'Es war kein Abschied. Es war nur das erste Mal, dass keiner von beiden zurückblieb.'
];
const FUNKE_FIGUREN = [
  'Jemand, der jeden Morgen denselben Satz übt, für einen Anruf, den er nie tätigt.',
  'Eine Frau, die alle Geburtstage ihrer Straße kennt, aber nicht ihren eigenen.',
  'Ein Mann, der Menschen nur nach ihrem Gang erkennt — und seine Tochter heute nicht erkennt.',
  'Ein Kind, das Erwachsene tröstet, ohne zu wissen, warum sie traurig sind.',
  'Eine Ärztin, die ihre Patienten an der Handschrift ihrer Rezepte wiedererkennt — Jahrzehnte später.',
  'Jemand, der nie nein sagen konnte und heute zum ersten Mal möchte.',
  'Ein alter Mann, der noch immer Briefe an eine Adresse schreibt, die es nicht mehr gibt.',
  'Eine Busfahrerin, die jede Haltestelle mit einem anderen Satz ansagt.',
  'Ein Junge, der vorgibt, taub zu sein, um endlich in Ruhe zuzuhören.',
  'Eine Frau, die in jeder Wohnung, in der sie je wohnte, einen Gegenstand versteckt hat.',
  'Ein Koch, der nur kocht, was er gerade fühlt, und keine Speisekarte hat.',
  'Die Schwester, die immer schon da war, wenn etwas passierte — zu oft, um Zufall zu sein.',
  'Ein Nachtwächter, der Angst im Dunkeln hat.',
  'Eine Frau, die Flaschenpost sammelt und alle Briefe beantwortet.',
  'Der Mann, der die Straßen der Stadt so gut kennt, dass er sich absichtlich verläuft.',
  'Ein Mädchen, das Gedichte für Haustiere schreibt, die gestorben sind.',
  'Ein Vater, der seinen Kindern das Lügen beibringt, damit sie es erkennen.',
  'Eine Schauspielerin, die nur eine Rolle spielen kann: sich selbst, als sie jünger war.',
  'Jemand, der mit Gegenständen spricht und ihnen zuhört.',
  'Ein Mann, der nie ein Foto von sich machen ließ — bis heute.',
  'Eine Frau, die Träume nicht behält, sondern sie weiterverschenkt.',
  'Ein Postbote, der jeden Brief einmal ans Ohr hält.',
  'Ein Kind, das Wörter sammelt, die Erwachsene nur einmal sagen.',
  'Die Nachbarin, die jeden Tag einen Stuhl auf den Balkon stellt, für jemanden, der nicht kommt.',
  'Ein Musiker, der seine Lieder nicht aufschreibt, weil sie dann sterben, sagt er.',
  'Eine Archivarin, die Briefe liest, die nie angekommen sind — und manchmal antwortet.',
  'Jemand, der so lange auf Reisen war, dass ihn die Stadt nicht wiedererkennt.',
  'Ein Lehrer, der seine Schüler nach zwanzig Jahren einzeln besucht, um etwas zurückzunehmen.',
  'Eine Frau, die zu jeder Mahlzeit für eine Person zu viel deckt — und genau weiß, für wen.',
  'Ein Junge, der sein Heimweh in einer Schachtel aufbewahrt und nur sonntags hineinsieht.'
];
const FUNKE_WENDUNGEN = [
  'Die Person, auf die gewartet wird, ist die ganze Zeit schon im Haus.',
  'Der Brief war an jemand anderen adressiert. Der Inhalt stimmt trotzdem.',
  'Sie hatte Recht. Das war das Schlimmste daran.',
  'Das Geräusch kam nicht von draußen.',
  'Der Fremde kennt das Ende der Geschichte — weil er sie schon einmal erzählt hat.',
  'Es war kein Zufall. Es war ein Versprechen von vor zwanzig Jahren.',
  'Der Anruf kam aus der eigenen Wohnung.',
  'Die Lüge stellte sich als die einzige Wahrheit heraus, an die sich alle halten konnten.',
  'Das Haus wurde verkauft — an die Person, die es einst angezündet hatte.',
  'Die Schwester war nie verschwunden. Sie wurde nur nie gesucht.',
  'Es regnet — aber nur auf der Straße, in der sie wohnt.',
  'Der Schlüssel passt. Die Wohnung gehört jemand anderem.',
  'Er war gar nicht gekommen, um sich zu entschuldigen. Er war gekommen, um es noch einmal zu tun.',
  'Das Foto war kein Beweis. Es war eine Einladung.',
  'Die Nachricht war dreißig Jahre alt — und trotzdem für heute gemeint.',
  'Der Hund hat sie nicht beschützt. Er hat sie bewacht.',
  'Das Versprechen wurde gehalten. Nur an die falsche Person.',
  'Die Tür war nie abgeschlossen. Niemand hatte es je versucht.',
  'Sie wollte nicht gehen. Sie wollte, dass man sie bittet zu bleiben.',
  'Er fand die Antwort — in einem Brief, den er selbst geschrieben hatte.',
  'Der Zug hatte Verspätung, weil jemand auf den Gleisen stand. Es war die Person, die sie besuchen wollte.',
  'Das Kind hatte die ganze Zeit die Wahrheit gesagt.',
  'Die beiden hatten sich nie getroffen. Sie erinnerten sich nur an dieselbe Geschichte.',
  'Das Licht im Nachbarhaus brennt, weil jemand auf sie wartet — seit Jahren.',
  'Es war nicht ihr Name auf dem Grabstein. Es war ihre Handschrift.'
];

/* Die Arten, die es gibt — eine Quelle fuer Zuhause, Woerter und Tests. */
const FUNKE_ARTEN = [['szene', 'Szene'], ['kombi', 'Wer · Wo · Aber'], ['figur', 'Figur'], ['wendung', 'Wendung'], ['frage', 'Frage'], ['form', 'Form'], ['satz', 'Satz']];
function neuerFunke(kombi, art) {
  if (art === 'frage') return zufall(FUNKE_FRAGEN);
  if (art === 'form') return zufall(FUNKE_FORMEN);
  if (art === 'satz') return zufall(FUNKE_SAETZE);
  if (art === 'figur') return zufall(FUNKE_FIGUREN);
  if (art === 'wendung') return zufall(FUNKE_WENDUNGEN);
  if (kombi) return zufall(FUNKE_WER) + ' ' + zufall(FUNKE_WO) + ' ' + zufall(FUNKE_ABER);
  return zufall(FUNKEN);
}
function funkeDesTages() {
  const k = tagKey();
  let h = 0;
  for (const c of k) h = (h * 31 + c.charCodeAt(0)) >>> 0;
  return FUNKEN[h % FUNKEN.length];
}

const SAATWORTE = ['flirren', 'windschief', 'Nachklang', 'Lichtsaum', 'aufgeraut', 'zwischenblau', 'verwunschen', 'Splittergold', 'seidenmatt', 'herzwärts'];

const HEFTFARBEN = [
  '#8c5a3b', '#6f4334', '#9a7657', '#b58d67', '#5b4a6e', '#75617f',
  '#3f6258', '#55776d', '#6d7d69', '#7a4048', '#955a5f', '#41597a',
  '#5c718a', '#736a34', '#8b8050', '#4a4a52', '#6b6a70', '#28333c',
  '#a56c49', '#c0a278', '#6c5848', '#344a43', '#583f52', '#38465d'
];
const HEFT_MUSTER = [
  ['schlicht', 'Schlicht'], ['leinen', 'Leinen'], ['diagonal', 'Diagonal'],
  ['punkte', 'Punkte'], ['rahmen', 'Rahmen'], ['welle', 'Wellen']
];
const SZENENFARBEN = ['', '#b0552f', '#5f7752', '#b8923f', '#41597a', '#7a4048'];
const PROJEKT_ARTEN = ['Roman', 'Erzählung', 'Sammlung', 'Gedichte', 'Welt', 'Anderes'];
